apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fplugin-qa
  annotations:
    kubernetes.io/ingress.global-static-ip-name: fplugin-qa
  labels:
    app: fplugin-qa
spec:
  backend:
    serviceName: fplugin-qa
    servicePort: 8080
---
apiVersion: v1
kind: fplugin-qa
metadata:
  name: fplugin-qa
  namespace: default
  labels:
    app: fplugin-qa
spec:
  type: NodePort
  selector:
    app: fplugin-qa
  ports:
  - port: 8080
    targetPort: 8080
